Реализация функционала вывода рекомендаций
Mikhail-Khazov/java-filmorate pull request #14
Opened 2022-12-24 20:13 UTC by Nalmezel1

2022-12-24 20:50 UTC, B10nicle approved these changes

2022-12-24 20:50 UTC, B10nicle approved these changes
согласовано

2022-12-24 22:38 UTC, AndrSlav13 approved these changes
Работа понравилась.

2022-12-25 08:53 UTC, merged

2022-12-25 09:08 UTC, Mikhail-Khazov requested changes